package bindings

import (
	"os"
	"strings"

	toolspec "github.com/hydrocode-de/tool-spec-go"
)

type JavaScriptPlainGenerator struct{}

func (g *JavaScriptPlainGenerator) Generate(spec toolspec.ToolSpec, outputPath string) error {
	_ = spec
	var buf strings.Builder
	buf.WriteString(jsPlainTemplate)
	return os.WriteFile(outputPath, []byte(buf.String()), 0644)
}

const jsPlainTemplate = `// AUTO-GENERATED by gotap - do not edit
import { execSync } from "child_process";
import { appendFileSync } from "fs";

const INPUT_FILE = "/in/input.json";
const SPEC_FILE = "/src/tool.yml";

function loadInput() {
  const cmd = "gotap parse --input-file " + INPUT_FILE + " --spec-file " + SPEC_FILE;
  const out = execSync(cmd, { encoding: "utf-8" });
  return JSON.parse(out);
}

export function getParameters() {
  const data = loadInput();
  return data.parameters;
}

export function getData() {
  const data = loadInput();
  return data.data;
}

export function getRunContext() {
  return {
    run_id: process.env.GOTAP_RUN_ID || "",
    log_file: process.env.GOTAP_LOG_FILE || "",
    log_format: process.env.GOTAP_LOG_FORMAT || "jsonl",
    log_level: process.env.GOTAP_LOG_LEVEL || "info",
  };
}

function writeLogLine(context, payload) {
  const line = JSON.stringify(payload) + "\n";
  if (context.log_file) {
    appendFileSync(context.log_file, line, "utf-8");
    return;
  }
  process.stderr.write(line);
}

export function getLogger() {
  const context = getRunContext();
  const log = (level, event, message, fields = {}) => {
    writeLogLine(context, {
      ts: new Date().toISOString(),
      level,
      event,
      message,
      run_id: context.run_id,
      ...fields,
    });
  };

  return {
    log,
    debug: (event, message, fields = {}) => log("debug", event, message, fields),
    info: (event, message, fields = {}) => log("info", event, message, fields),
    warn: (event, message, fields = {}) => log("warn", event, message, fields),
    error: (event, message, fields = {}) => log("error", event, message, fields),
  };
}
`
