package bindings

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"text/template"

	toolspec "github.com/hydrocode-de/tool-spec-go"
)

type JavaScriptGenerator struct{}

func (g *JavaScriptGenerator) Generate(spec toolspec.ToolSpec, outputPath string) error {
	tmpl, err := template.New("javascript").Parse(jsTemplate)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}

	paramNames := make([]string, 0, len(spec.Parameters))
	for name := range spec.Parameters {
		paramNames = append(paramNames, name)
	}
	sort.Strings(paramNames)

	dataNames := make([]string, 0, len(spec.Data))
	for name := range spec.Data {
		dataNames = append(dataNames, name)
	}
	sort.Strings(dataNames)

	paramFields := make([]jsField, 0, len(paramNames))
	for _, name := range paramNames {
		p := spec.Parameters[name]
		paramFields = append(paramFields, jsField{Name: name, Type: g.paramTypeToJS(&p), JSDoc: p.Description})
	}

	dataFields := make([]jsField, 0, len(dataNames))
	for _, name := range dataNames {
		dataFields = append(dataFields, jsField{Name: name, Type: "string", JSDoc: spec.Data[name].Description})
	}

	data := struct {
		ParamFields []jsField
		DataFields  []jsField
	}{ParamFields: paramFields, DataFields: dataFields}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("execute template: %w", err)
	}

	return os.WriteFile(outputPath, []byte(buf.String()), 0644)
}

type jsField struct {
	Name  string
	Type  string
	JSDoc string
}

func (g *JavaScriptGenerator) paramTypeToJS(p *toolspec.ParameterSpec) string {
	if p.IsArray {
		return g.scalarTypeToJS(p.ToolType) + "[]"
	}
	return g.scalarTypeToJS(p.ToolType)
}

func (g *JavaScriptGenerator) scalarTypeToJS(toolType string) string {
	switch toolType {
	case "integer", "float":
		return "number"
	case "string", "asset", "enum", "datetime", "date", "time":
		return "string"
	case "boolean":
		return "boolean"
	default:
		return "unknown"
	}
}

const jsTemplate = `// AUTO-GENERATED by gotap - do not edit
import { execSync } from "child_process";

const INPUT_FILE = "/in/input.json";
const SPEC_FILE = "/src/tool.yml";

export interface Parameters {
{{- range .ParamFields}}
  {{.Name}}: {{.Type}};
{{- end}}
}

export interface DataPaths {
{{- range .DataFields}}
  {{.Name}}: string;
{{- end}}
}

export interface ToolInput {
  parameters: Parameters;
  data: DataPaths;
}

export function getParameters(): Parameters {
  const cmd = "gotap parse --input-file " + INPUT_FILE + " --spec-file " + SPEC_FILE;
  const out = execSync(cmd, { encoding: "utf-8" });
  const data: ToolInput = JSON.parse(out);
  return data.parameters;
}

export function getData(): DataPaths {
  const cmd = "gotap parse --input-file " + INPUT_FILE + " --spec-file " + SPEC_FILE;
  const out = execSync(cmd, { encoding: "utf-8" });
  const data: ToolInput = JSON.parse(out);
  return data.data;
}
`