package bindings

import (
	"os"
	"strings"

	toolspec "github.com/hydrocode-de/tool-spec-go"
)

type JavaScriptPlainGenerator struct{}

func (g *JavaScriptPlainGenerator) Generate(spec toolspec.ToolSpec, outputPath string) error {
	_ = spec
	var buf strings.Builder
	buf.WriteString(jsPlainTemplate)
	return os.WriteFile(outputPath, []byte(buf.String()), 0644)
}

const jsPlainTemplate = `// AUTO-GENERATED by gotap - do not edit
import { execSync } from "child_process";

const INPUT_FILE = "/in/input.json";
const SPEC_FILE = "/src/tool.yml";

export function getParameters() {
  const cmd = "gotap parse --input-file " + INPUT_FILE + " --spec-file " + SPEC_FILE;
  const out = execSync(cmd, { encoding: "utf-8" });
  const data = JSON.parse(out);
  return data.parameters;
}

export function getData() {
  const cmd = "gotap parse --input-file " + INPUT_FILE + " --spec-file " + SPEC_FILE;
  const out = execSync(cmd, { encoding: "utf-8" });
  const data = JSON.parse(out);
  return data.data;
}
`