package bindings

import (
	"os"
	"strings"

	toolspec "github.com/hydrocode-de/tool-spec-go"
)

type MatlabGenerator struct{}

func (g *MatlabGenerator) Generate(spec toolspec.ToolSpec, outputPath string) error {
	_ = spec
	var buf strings.Builder
	buf.WriteString("% AUTO-GENERATED by gotap - do not edit\n\n")

	buf.WriteString("function [params, data] = get_parameters(input_file, spec_file)\n")
	buf.WriteString("% get_parameters Parse tool input using gotap\n")
	buf.WriteString("%   Returns params struct with parameter values and data struct with file paths\n")
	buf.WriteString("    if nargin < 1\n")
	buf.WriteString("        input_file = '/in/input.json';\n")
	buf.WriteString("    end\n")
	buf.WriteString("    if nargin < 2\n")
	buf.WriteString("        spec_file = '/src/tool.yml';\n")
	buf.WriteString("    end\n")
	buf.WriteString("    [status, result] = system(['gotap parse --input-file ' input_file ' --spec-file ' spec_file]);\n")
	buf.WriteString("    if status ~= 0\n")
	buf.WriteString("        error('gotap parse failed: %s', result);\n")
	buf.WriteString("    end\n")
	buf.WriteString("    json_data = jsondecode(result);\n")
	buf.WriteString("    params = json_data.parameters;\n")
	buf.WriteString("    data = json_data.data;\n")
	buf.WriteString("end\n")

	return os.WriteFile(outputPath, []byte(buf.String()), 0644)
}
