package bindings

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"text/template"

	toolspec "github.com/hydrocode-de/tool-spec-go"
)

type PythonGenerator struct{}

func (g *PythonGenerator) Generate(spec toolspec.ToolSpec, outputPath string) error {
	tmpl, err := template.New("python").Parse(pythonTemplate)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, g.buildTemplateData(spec)); err != nil {
		return fmt.Errorf("execute template: %w", err)
	}

	return os.WriteFile(outputPath, []byte(buf.String()), 0644)
}

type pythonTemplateData struct {
	ClassName     string
	ParamFields   []pythonField
	DataFields    []pythonField
	NeedsLiteral  bool
	InputFile     string
	SpecFile      string
}

type pythonField struct {
	Name string
	Type string
}

func (g *PythonGenerator) buildTemplateData(spec toolspec.ToolSpec) pythonTemplateData {
	paramNames := make([]string, 0, len(spec.Parameters))
	for name := range spec.Parameters {
		paramNames = append(paramNames, name)
	}
	sort.Strings(paramNames)

	dataNames := make([]string, 0, len(spec.Data))
	for name := range spec.Data {
		dataNames = append(dataNames, name)
	}
	sort.Strings(dataNames)

	paramFields := make([]pythonField, 0, len(paramNames))
	needsLiteral := false
	for _, name := range paramNames {
		p := spec.Parameters[name]
		pyType := g.paramTypeToPython(&p)
		if strings.HasPrefix(pyType, "Literal[") {
			needsLiteral = true
		}
		paramFields = append(paramFields, pythonField{Name: name, Type: pyType})
	}

	dataFields := make([]pythonField, 0, len(dataNames))
	for _, name := range dataNames {
		dataFields = append(dataFields, pythonField{Name: name, Type: "str"})
	}

	className := toPascalCase(spec.Name)
	if className == "" {
		className = "Parameters"
	}

	return pythonTemplateData{
		ClassName:    className,
		ParamFields:  paramFields,
		DataFields:   dataFields,
		NeedsLiteral: needsLiteral,
		InputFile:    "/in/input.json",
		SpecFile:     "/src/tool.yml",
	}
}

func (g *PythonGenerator) paramTypeToPython(p *toolspec.ParameterSpec) string {
	base := p.ToolType
	if p.IsArray {
		elem := g.scalarTypeToPython(base, p)
		return "List[" + elem + "]"
	}
	return g.scalarTypeToPython(base, p)
}

func (g *PythonGenerator) scalarTypeToPython(toolType string, p *toolspec.ParameterSpec) string {
	switch toolType {
	case "integer":
		return "int"
	case "float":
		return "float"
	case "string", "asset":
		return "str"
	case "boolean":
		return "bool"
	case "enum":
		if len(p.Values) > 0 {
			vals := make([]string, len(p.Values))
			for i, v := range p.Values {
				vals[i] = `"` + v + `"`
			}
			return `Literal[` + strings.Join(vals, ", ") + `]`
		}
		return "str"
	case "datetime", "date", "time":
		return "str"
	default:
		return "Any"
	}
}

func toPascalCase(s string) string {
	if s == "" {
		return ""
	}
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(string(p[0])) + strings.ToLower(p[1:])
		}
	}
	return strings.Join(parts, "")
}

const pythonTemplate = `# AUTO-GENERATED by gotap - do not edit
from dataclasses import dataclass
from typing import List{{if .NeedsLiteral}}, Literal{{end}}, Any
import json
import subprocess

@dataclass
class {{.ClassName}}:
{{- range .ParamFields}}
    {{.Name}}: {{.Type}}
{{- end}}
{{- if .DataFields}}

@dataclass
class DataPaths:
{{- range .DataFields}}
    {{.Name}}: str
{{- end}}
{{- end}}

def get_parameters() -> {{.ClassName}}:
    out = subprocess.check_output(
        ["gotap", "parse", "--input-file", "{{.InputFile}}", "--spec-file", "{{.SpecFile}}"],
        text=True
    )
    data = json.loads(out)
    return {{.ClassName}}(**data["parameters"])
{{if .DataFields}}

def get_data() -> dict[str, str]:
    out = subprocess.check_output(
        ["gotap", "parse", "--input-file", "{{.InputFile}}", "--spec-file", "{{.SpecFile}}"],
        text=True
    )
    data = json.loads(out)
    return data["data"]
{{end}}
`
