package bindings

import (
	"os"
	"strings"

	toolspec "github.com/hydrocode-de/tool-spec-go"
)

type RGenerator struct{}

func (g *RGenerator) Generate(spec toolspec.ToolSpec, outputPath string) error {
	_ = spec
	var buf strings.Builder
	buf.WriteString("# AUTO-GENERATED by gotap - do not edit\n\n")

	buf.WriteString("get_parameters <- function(input_file = \"/in/input.json\", spec_file = \"/src/tool.yml\") {\n")
	buf.WriteString("  result <- system2(\"gotap\", c(\"parse\", \"--input-file\", input_file, \"--spec-file\", spec_file), stdout = TRUE)\n")
	buf.WriteString("  data <- jsonlite::fromJSON(paste(result, collapse = \"\\n\"))\n")
	buf.WriteString("  list(parameters = data$parameters, data = data$data)\n")
	buf.WriteString("}\n")

	return os.WriteFile(outputPath, []byte(buf.String()), 0644)
}
