package bindings

import (
	"os"
	"strings"

	toolspec "github.com/hydrocode-de/tool-spec-go"
)

type RGenerator struct{}

func (g *RGenerator) Generate(spec toolspec.ToolSpec, outputPath string) error {
	_ = spec
	var buf strings.Builder
	buf.WriteString("# AUTO-GENERATED by gotap - do not edit\n\n")

	buf.WriteString("load_input <- function(input_file = \"/in/input.json\", spec_file = \"/src/tool.yml\") {\n")
	buf.WriteString("  result <- system2(\"gotap\", c(\"parse\", \"--input-file\", input_file, \"--spec-file\", spec_file), stdout = TRUE)\n")
	buf.WriteString("  data <- jsonlite::fromJSON(paste(result, collapse = \"\\n\"))\n")
	buf.WriteString("  data\n")
	buf.WriteString("}\n\n")

	buf.WriteString("get_parameters <- function(input_file = \"/in/input.json\", spec_file = \"/src/tool.yml\") {\n")
	buf.WriteString("  data <- load_input(input_file, spec_file)\n")
	buf.WriteString("  list(parameters = data$parameters, data = data$data)\n")
	buf.WriteString("}\n\n")

	buf.WriteString("get_run_context <- function() {\n")
	buf.WriteString("  list(\n")
	buf.WriteString("    run_id = Sys.getenv(\"GOTAP_RUN_ID\", unset = \"\"),\n")
	buf.WriteString("    log_file = Sys.getenv(\"GOTAP_LOG_FILE\", unset = \"\"),\n")
	buf.WriteString("    log_format = Sys.getenv(\"GOTAP_LOG_FORMAT\", unset = \"jsonl\"),\n")
	buf.WriteString("    log_level = Sys.getenv(\"GOTAP_LOG_LEVEL\", unset = \"info\")\n")
	buf.WriteString("  )\n")
	buf.WriteString("}\n\n")

	buf.WriteString("get_logger <- function() {\n")
	buf.WriteString("  context <- get_run_context()\n")
	buf.WriteString("  write_log <- function(level, event, message, fields = list()) {\n")
	buf.WriteString("    payload <- c(list(\n")
	buf.WriteString("      ts = format(Sys.time(), \"%Y-%m-%dT%H:%M:%OS3Z\", tz = \"UTC\"),\n")
	buf.WriteString("      level = level,\n")
	buf.WriteString("      event = event,\n")
	buf.WriteString("      message = message,\n")
	buf.WriteString("      run_id = context$run_id\n")
	buf.WriteString("    ), fields)\n")
	buf.WriteString("    line <- paste0(jsonlite::toJSON(payload, auto_unbox = TRUE, null = \"null\"), \"\\n\")\n")
	buf.WriteString("    if (nzchar(context$log_file)) {\n")
	buf.WriteString("      cat(line, file = context$log_file, append = TRUE)\n")
	buf.WriteString("    } else {\n")
	buf.WriteString("      cat(line, file = stderr())\n")
	buf.WriteString("    }\n")
	buf.WriteString("  }\n")
	buf.WriteString("  list(\n")
	buf.WriteString("    log = write_log,\n")
	buf.WriteString("    debug = function(event, message, ...) write_log(\"debug\", event, message, list(...)),\n")
	buf.WriteString("    info = function(event, message, ...) write_log(\"info\", event, message, list(...)),\n")
	buf.WriteString("    warn = function(event, message, ...) write_log(\"warn\", event, message, list(...)),\n")
	buf.WriteString("    error = function(event, message, ...) write_log(\"error\", event, message, list(...))\n")
	buf.WriteString("  )\n")
	buf.WriteString("}\n")

	return os.WriteFile(outputPath, []byte(buf.String()), 0644)
}
